CC = g++
CFLAGS  = -Wall

main: main.o node.o transaction.o
	${CC} ${CFLAGS} -o netw main.o node.o transaction.o

main.o: main.cpp
	${CC} ${CFLAGS} -c main.cpp

node.o: node.hpp
 
transaction.o: transaction.hpp

clean:
	rm netw
