CC = g++
CFLAGS  = -Wall

main: main.o node.o transaction.o task.o latency.o
	${CC} ${CFLAGS} -o netw main.o node.o transaction.o task.o latency.o

main.o: main.cpp
	${CC} ${CFLAGS} -c main.cpp

node.o: node.hpp
 
transaction.o: transaction.hpp

latency.o: latency.hpp

task.o: task.hpp

clean:
	rm netw
